### ISSUE TITLE
Not stacking?

### ISSUE THREAD

**Issue by Xogue** [Zazsona/DecorHeads#1] opened 2021-03-04 16:43 UTC
Dunno if It is supposed to be that way. but an update a while ago made the heads stop stacking. I use it on my sub server and the admins and I thought it would change back, but it hasnt. getting to the point that we may need to remove them.

**Comment by Roan-V** [comment] 2021-03-04 17:53
Can confirm.
After some quick testing it seems that V3.1 broke the stacking, it's fine in V3.0
Using purpur#980 (1.16.5) and J11

**Comment by Zazsona** [comment] 2021-03-04 18:23
Thanks for reporting @Xogue , and for getting me the version @Roan-V !
I must admit, I've got a few too many chests of single dirt heads of my own after a bit of terraforming, would be nice if those sods were stacking! Going by the V3.0 -> V3.1 timeframe and reviewing the commits, I'm almost certain the offending commit is: [Fix a bug where head textures wouldn't load on Spigot 1.16+](https://github.com/Zazsona/DecorHeads/commit/56707c08958616d95224e4779dfd9cbed8a7aff7), which changed how heads are generated.

No guarantees, but I have a couple of ideas on what may be the cause, so I'll see to having a sniff around this weekend! Thanks guys.

**Comment by Zazsona** [comment] 2021-03-06 15:01
Thanks again for reporting, this has now been fixed in 1.5.1! It's available on [Spigot](https://www.spigotmc.org/resources/decorheads.88633/update?update=391040) and awaiting review on [Bukkit](https://dev.bukkit.org/projects/decorheads)

**Closed as completed by Zazsona** 2021-03-06 15:01 UTC
Labels: bug

**Comment by Roan-V** [comment] 2021-03-07 14:38
Yep, latest update fixed it for us!
Thank you for taking the time, great plugin!
